repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: [ --maxkb=1024, --enforce-all ]
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix, lf ]
