FROM debian:12 as basic

ENV DEBIAN_FRONTEND noninteractive
ENV TZ Etc/UTC

RUN apt-get update \
    && apt-get install -y ca-certificates sed \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y python3 sudo build-essential systemd systemd-sysv net-tools lshw python-apt-common \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN groupadd --gid 1000 rootless \
    && useradd --gid rootless --uid 1000 --shell /bin/bash --create-home rootless \
    && chown --recursive rootless:rootless /home/rootless \
    && echo 'rootless  ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

FROM basic as with_docker

RUN apt-get update \
    && apt-get install -y apt-transport-https curl gnupg lsb-release python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg  \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null  \
    && apt-get update -y  \
    && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && systemctl enable docker \
    && usermod -a -G docker rootless
RUN pip install --no-cache-dir --break-system-packages docker docker-compose PyYAML==5.3.1
