FROM ubuntu:22.04 as base

RUN apt-get update \
    && apt-get install -y python3.11 ca-certificates curl sed podman \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install python requirements
RUN pip install pipenv ansible-core

# uid 1001 to be compatible with the default GitHub action user
RUN groupadd --gid 1001 podman \
    && useradd --gid podman --uid 1001 --shell /bin/bash --create-home podman \
    && chown --recursive podman:podman /home/podman
ENV USER=podman

COPY podman.conf /etc/containers/containers.conf

RUN apt-get update \
    && apt-get install -y net-tools git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER podman
RUN ansible-galaxy collection install containers.podman
